### ISSUE TITLE
Übungsblatt 1,Aufgabe 4 bearbeiten

### ISSUE THREAD

**Issue by m1n1** [sweIhm-ws2018-19/skillproject-do-3#1]
Aufgabe lösen bis zum 22.10.2018
Reviewer ist Tobi Stadler

**Comment by m1n1** [comment]
public class Konto {
    private String bezeichnung;
    private Kunde[] zeichnungsberechtigter;

    public Geldbetrag saldo();
    public void(Geldbetrag eingBetrag);
}

public abstract class Kunde{
    private Konto[] konto;
}

public class Privatkunde extends Kunde{
    private String vorname;
    private String nachname;
    private Adresse postAdresse;
}

public class Geschäftskunde extends Kunde{
    private String firmenname;
    private Adresse domizilAdresse;
}

public class Adresse{
    private String strasse;
    private int hausnummer;
    private String plz;
    private String ort;
}

**Comment by devtobi** [comment]
Ich hab deinen Code oben verbessert. Es war fast alles richtig. Klassennamen noch angepasst und das "ä" aus dem Geschäftskunden raus.

**Comment by m1n1** [comment]
Okay dann lade ich die Dateien hoch und schließe hier den Issue
