### ISSUE TITLE
Use-Case Alexa

### ISSUE THREAD

**Issue by hefeweizn55** [sweIhm-ws2018-19/skillproject-do-3#10]
Hoi, passt des so, oder würdet ihr evtl. noch bei Portfolioinhalt abfragen etwas ändern?

![ucalexa](https://user-images.githubusercontent.com/43846346/48285261-52b01700-e462-11e8-83bf-059a10f80582.png)

**Comment by m1n1** [comment]
Wert des Portfolios abfragen und Wert des Portfolios in der Vergangehnheit abfragen sollten noch dabei sein. Und auf jeden Fall sollte noch Hilfe dabei sein. 

Im grunde kannst es 1 zu 1 von unserem statischen Prototypen uebernehmen.
https://getstoryline.com/shared/projects/99d46cdcd4a0a4c4fac95b57233e936c84926fb2

**Comment by devtobi** [comment]
1."Alexa begruessen" finde ich nicht richtig. Es sollte eher "CryptoGuide starten" heißen.
2."Kryptokurse abfragen" würde ich splitten in einmal die Abfrage eines aktuellen Kurses und eines Kurses aus der Vergangenheit (Und Kryptokurse abfragen dann als übergeordneten Use Case)
3."Kryptokurshistorie abfragen" würde ich "Kryptokursverlauf" oder "Kryptokursentwicklung" schreiben.
4."Portfolio anlegen/einstellen" zu "Portfolio editieren" umbennen.
5."Alexa verabschieden" umbennenen zu "CryptoGuide beenden".
6."Portfolioinhalt abfragen" splitten wie in Punkt 2.
7."Hilfe aufrufen" hinzufügen.

MfG Tobi

**Comment by devtobi** [comment]
Jetzt sieht das schon besser aus 👍

**Comment by hefeweizn55** [comment]
So, sollte jetzt so passen, werde noch einen 13. Punkt machen, da es durchaus praktisch ist, zu wissen, welche Kryptowährung zu welchem Zeitpunkt sich im Portfolio befunden hat, da man (glaub ich) steuertechnisch nach einem Jahr von der Spekulationssteuer befreit wird und somit noch einen Überblick hat.

![ucalexa](https://user-images.githubusercontent.com/43846346/48317319-64bfc000-e5f0-11e8-8fa0-01e11d2a550c.png)

**Comment by devtobi** [comment]
Dieser neue Use-Case den du da hinzugefügt hast in in der Realität ganz schwer zu implementieren, da du dir in einer Datenbank auch die alten Zustände speichern müsstest. Das macht das ganze nur unnötig schwer.
Lösch das bitte raus.

**Comment by hefeweizn55** [comment]
Ich finde das würde die Anwendung aber tatsächlich brauchbar machen, da du mit so einem Tool diese Steuergeschichte quasi belegen kannst. Es ist eigentlich fast das selbe, wie mit dem vergangenen Portfoliowert, nur, dass man halt da nicht den Wert ausgibt, sondern die Währung, das wäre nicht mal eine weitere Datenbank, sondern nur die Referenz auf die Währungsattribute. Quasi fast der gleiche Code...
