### ISSUE TITLE
Übungsblatt 2,Aufgabe 4 bearbeiten

### ISSUE THREAD

**Issue by ReneNeu** [sweIhm-ws2018-19/skillproject-do-3#3]
Aufgabe lösen bis zum 29.10.2018
Reviewer ist Tobias Stadler

**Comment by ReneNeu** [comment]
[Aufgabe 4.zip](https://github.com/sweIhm-ws2018-19/skillproject-do-3/files/2516223/Aufgabe.4.zip)

**Comment by devtobi** [comment]
Dein Guard beim Entscheidungsknoten würde ich anders formulieren. Eher so wie flashNeeded == true oder halt eben flashNeeded == false. Außerdem generiert quasi diese Aktion Daten und diese sind dann später bei der Aktion Blitz zünden wieder wichtig (Vorallem wie lange und wie stark geblitzt werden soll).
Deswegen würde ich so wie z.b hier https://goo.gl/images/xQsRXi einen Objektfluss von der Aktion "Blitzeinstellungen ermitteln" zu "Blitz zünden" darstellen.
Außerdem ist das Element, dass du zum Vereinen der beiden Pfade (Blitz zünden oder halt nicht) nicht korrekt. Du brauchst da ein Merge node (also wieder diese Raute, nur diesmal mit eingehenden Pfeilen und nur einem ausgehenden).

**Comment by ReneNeu** [comment]
Ich hab das Aktivitätsdiagramm dementsprechend angepasst.

[Aufgabe 4 Final.zip](https://github.com/sweIhm-ws2018-19/skillproject-do-3/files/2521646/Aufgabe.4.Final.zip)

**Comment by devtobi** [comment]
Jetzt sieht es gut aus. Kann geschlossen werden.
