### ISSUE TITLE
Uebungsblatt2, Aufgabe 3 bearbeiten

### ISSUE THREAD

**Issue by m1n1** [sweIhm-ws2018-19/skillproject-do-3#4]
Aufgabe lösen bis zum 29.10.2018
Reviewer ist Mario Bengazi

![aufgabe3](https://user-images.githubusercontent.com/43846168/47564115-32417200-d924-11e8-9a03-aa2ff049608d.jpg)

**Comment by m1n1** [comment]
Das Subsystem ist optional soweit ich ich das verstanden habe, hab es mal geloescht. Das mit Fahrt suchen habe ich geaendert.

![aufgabe3](https://user-images.githubusercontent.com/43846168/47603486-b65f2c80-d9ec-11e8-98f3-a363b8c4ba74.png)

**Comment by hefeweizn55** [comment]
Passt!
