### ISSUE TITLE
Übungsblatt 2, Aufgabe 7 bearbeiten

### ISSUE THREAD

**Issue by devtobi** [sweIhm-ws2018-19/skillproject-do-3#5]
Aufgabe lösen bis zum 29.10.2018
Reviewer ist Rene Neuhaus

![blatt2aufgabe7](https://user-images.githubusercontent.com/28538704/47577899-4f883780-d948-11e8-8eb0-baf75215fa15.png)

**Comment by devtobi** [comment]
Hab noch die Rollen eingefügt:
![blatt2aufgabe7](https://user-images.githubusercontent.com/28538704/47603186-d68cec80-d9e8-11e8-8d09-ba97e2ff127c.png)

**Comment by ReneNeu** [comment]
Ja genau so passt es. So würde ich es auch machen.
