### ISSUE TITLE
Übungsblatt 2, Aufgabe 1 bearbeiten

### ISSUE THREAD

**Issue by hefeweizn55** [sweIhm-ws2018-19/skillproject-do-3#6]
Aufgabe lösen bis zum 29.10.2018
Reviewer ist Mathias Weinstabl
![a1](https://user-images.githubusercontent.com/43846346/47600938-1f34ad80-d9c9-11e8-8bf9-84b3dedb05c2.png)

**Comment by m1n1** [comment]
Ich glaube die Blitz einstellungen stehen in einer Include-Beziehung zum Use-Case "Blitz einstellen". Fuer extend Beziehungen muss gelten: "Both use cases may be executed independently of each other." 

Das ist ja hier nicht der Fall, "Blitz einstellen" beinhaltet ja hier an sich keine Funktionalitaet. Deshalb muss sie meiner Meinung nach Inkludiert werden.
![image](https://user-images.githubusercontent.com/43846168/47603715-608c8380-d9f0-11e8-9551-ca51e64554c8.png)

Ausserdem gaebe es dann fuer jede Blase einen Punkt was glaube ich kein Zufall ist ;)

**Comment by hefeweizn55** [comment]
Merci, 
hab es wohl falsch verstanden gehabt, hier hab ich noch einen Link, der dass auch nochmal super erklärt:
https://www.youtube.com/watch?v=zid-MVo7M-E

hier die abgeänderte Version:
![a1final](https://user-images.githubusercontent.com/43846346/47606140-2fbc4680-da10-11e8-96d9-1882442f6b0d.png)

**Comment by m1n1** [comment]
Hm hab mir des Video auch mal kurz angeschaut. Ich glaube includes müssen immer ausgeführt werden und zwar alle. Hab da leider auch noch nicht perfekt durchschaut.

Schau mal ab 10:50 das Video ich glaube Generalisierung, auch Vererbung genannt ist das was wir brauchen. 

![image](https://user-images.githubusercontent.com/43846168/47606776-d2c48e80-da17-11e8-9fff-a3582d7333fe.png)

Bei der Aufgabe 3 ist das ja auch so das der Fahrer eine Fahrt angibt und dabei sich entscheidet ob es eine einfache Fahrt oder eine mit Zwischenziel ist.

**Comment by hefeweizn55** [comment]
So, kleine Ausbesserung:

![a1final](https://user-images.githubusercontent.com/43846346/47744251-343b6600-dc81-11e8-942e-e821197c4c1c.png)
