### ISSUE TITLE
Übungsblatt2, Aufgabe 8 bearbeiten

### ISSUE THREAD

**Issue by hefeweizn55** [sweIhm-ws2018-19/skillproject-do-3#7]
Reviewer: Mathias Weinstabl

![aufgabe8](https://user-images.githubusercontent.com/43846346/47607136-6b5d0d80-da1c-11e8-8842-e3c9fc9a83de.png)

**Comment by m1n1** [comment]
Ich hab den Text so verstanden das Dokument1 Dokument2 enthält und auch die Grafik zu Dokument1 gehört.

Die zusammengesetzte Grafik sollte auch noch die Parameter größe und position haben und dementsprechend einen Instanznamen. 

Sollte auch nicht jedes Dokument seinen eigenen Text bekommen? Wenn nicht kannst mir ja erklären wieso nicht.

**Comment by hefeweizn55** [comment]
So, hab noch das hier entdeckt:
https://www.youtube.com/watch?v=sTM0EjAit7c
Min: 5:19 
Da anscheinend Dokument1 ein Dokument2 enthält, sollte doch auch noch eine Objektbeziehung zwischen den Beiden bestehen.

![aufgabe8](https://user-images.githubusercontent.com/43846346/47747513-cd21af80-dc88-11e8-95f9-946db0d92e94.png)

**Comment by m1n1** [comment]
Ja da hast du vollkommen recht mein Text sollte auch so verstanden werden.

Das mit dem enthält kann man machen muss man aber nicht soweit ichs verstanden habe, hilft halt wenn es nicht klar ist.

Ich denke es sollte so passen also close ich mal hier.
