### ISSUE TITLE
Übungsblatt2, Aufgabe9 bearbeiten

### ISSUE THREAD

**Issue by m1n1** [sweIhm-ws2018-19/skillproject-do-3#8]
Reviewer ist Mario Begazo.

![aufgabe9](https://user-images.githubusercontent.com/43846168/47615917-4d43eb80-dab6-11e8-9115-572957795372.png)

Edit: Das erste drucken ist beim exportieren irgendwie in den Pfeil gerutscht, wird beim naechsten Review gefixt.

**Comment by hefeweizn55** [comment]
Hoi, 
- Die Objekte müssen in Rechtecken stehen. 
Auf Seite 304 (Analyse und Design mit der UML  2.5) zeigen abgerundete Ecken einen Zustand an.
- Wenn wir davon ausgehen, dass drucken tatsächlich ausgeführt wird, sollten wir true anstatt bool über die gestrichelten Pfeile schreiben. Wenn wir beide Möglichkeiten anzeigen wollen, evtl. true/false.
Da bin ich mir jetzt nicht sicher, ob das auch funktioniert...
https://www.youtube.com/watch?v=16VdlGiHTq0
Min: 2:24
Ansonsten schaut es gut aus.

**Comment by m1n1** [comment]
![aufgabe9](https://user-images.githubusercontent.com/43846168/47777990-2bd14280-dcf6-11e8-9ccb-484db2988324.png)

Ich denke das mit bool als Rueckgabewert sollte passen. true/false ist ja das gleiche als bool. Ausserdem habe ich keine Informationen um die rueckgabe zu spezifizieren.

**Comment by devtobi** [comment]
Ich geb hier mal meinen Senf dazu auch wenn ich nicht der Reviewer bin. Ich finde das sieht alles sehr gut aus und deswegen sollte der Isssue geschlossen werden.
