### ISSUE TITLE
Übungsblatt 2 Aufgabe 6 bearbeiten

### ISSUE THREAD

**Issue by devtobi** [sweIhm-ws2018-19/skillproject-do-3#9]
Erledigen bis 01.11.2018 18:00 Uhr
Reviewer ist: Mathias Weinstabl

**Comment by ReneNeu** [comment]
[Aufgabe 6.zip](https://github.com/sweIhm-ws2018-19/skillproject-do-3/files/2535832/Aufgabe.6.zip)

**Comment by m1n1** [comment]
Zuerst würde ich oben noch Bestellung geht ein oder ähnliches schreiben und eine Kundendatenbank mit "Kundendaten aus Bestellung abrufen" verbinden. Dann muss man das nicht so zusätzlich verzweigen.

Theoretisch kann man im ganzen Diagramm wo Datenbanken involviert sind das hinzufügen, jedoch bin ich mit unsicher wie weit hier spezifiziert werden muss.

Desweiteren kann man als final node noch hinzufügen wenn kein Artikel aus der Liste verfügbar war

**Comment by ReneNeu** [comment]
![aufgabe6](https://user-images.githubusercontent.com/43846116/47848365-6b6b5d80-ddce-11e8-8dfe-4f785cf1f8ac.png)
